### ISSUE TITLE
Makefile lacks demo target

### ISSUE THREAD

**Issue by smontanaro** [peopledoc/django-chartjs#10]
The Makefile lacks a demo target, yet demo/README includes these instructions:

   git clone git@github.com:novagile/django-chartjs.git
   cd django-chartjs/
   make demo

It installs and runs the demo server on localhost, port 8000. So have a look
at http://localhost:8000/

For someone unfamiliar with Django, a working demo would be great.

**Comment by matthewbrawley** [comment]
Any luck with this? I can't get the demo to work either

**Comment by marauder37** [comment]
I don't think the Makefile ever had a demo target so I hacked one in

**Comment by Natim** [comment]
Thanks @marauder37 for tackling this!
