### ISSUE TITLE
Class naming inconsistent

### ISSUE THREAD

**Issue by jimr** [peopledoc/django-chartjs#12]
For example, `Highcharts` versus `Highchart` versus `HighCharts` (the first is correct as per their website), and the use of the `Base` prefix. I would propose something like this:
- `HighChartsView` -> `HighchartsView`
- `BaseColumnsHighChartsView` -> `HighchartsColumnView`
- `HighchartPlotLineChartView` -> `HighchartsLineView`
- `HighChartPieView` -> `HighchartsPieView`
- `HighChartDonutView` -> `HighchartsDonutView`

Additionally, `BaseLineChartView` isn't subclassed by anything - should it be (maybe `HighchartPlotLineChartView`)?

**Comment by Natim** [comment]
@jimr would you like to fix this?
