### ISSUE TITLE
Chart.min.js is too old

### ISSUE THREAD

**Issue by g1itch** [peopledoc/django-chartjs#14]
Chart.js 1.0.2 released 27 days ago. Please update your static. Chart.min.js bundled with package does not contain even an `.addData (valuesArray, label)`.

**Comment by Natim** [comment]
Do you mind doing a PR for that please?

**Comment by marauder37** [comment]
Are there any plans to update the bundled version of Chart.js? The current version is 2.5.0.

**Comment by Natim** [comment]
@marauder37 I would be glad to merge your pull-request if you can put one together.
