### ISSUE TITLE
Highcharts implementation

### ISSUE THREAD

**Issue by AlejandroHCruz** [peopledoc/django-chartjs#21]
Hi, I'm trying to show a Highcharts spline chart based on the demo code provided here but I'm getting this error: `Uncaught TypeError: Cannot read property 'draw' of undefinedi.Type.extend.draw @ Chart.min.js:11l @ Chart.min.js:10`

Could you guys upload a fully functional highcharts example?

Thanks!

**Comment by wo0dyn** [comment]
Issue addressed in #30 — Thanks to @marauder37
