### ISSUE TITLE
Not displaying Pie chart in Django

### ISSUE THREAD

**Issue by setivolkylany** [peopledoc/django-chartjs#22]
Hi authors django-chartit, I have bit problem with your labour. See detail here http://stackoverflow.com/questions/36179624/right-displaying-pie-chart-in-django-with-help-django-chartjs.

May somebody known how right working with django-charjs and building pie chart

Thanks

**Comment by lorinwu** [comment]
still meet the same issue

**Comment by robertpro** [comment]
@padymkoclab why did you remove the question on SO? I don't have context about the issue anymore.

**Comment by Natim** [comment]
@robertpro 

There you go!

![image](https://user-images.githubusercontent.com/229453/183945374-46b4bda1-f851-4a0e-866a-ca6d66ea8a58.png)

**Comment by robertpro** [comment]
@Natim thanks!
