### ISSUE TITLE
Issue in demo project.

### ISSUE THREAD

**Issue by subrat26** [peopledoc/django-chartjs#29]
Its using old version of chart.js line function in line_chart.html

Should be updated to
        <script type="text/javascript">
            $.get('{% url 'line_chart_json' %}', function(data) {
                var ctx = $("#myChart").get(0).getContext("2d");
                new Chart(ctx, {
            type: "line",
            data: data, 
        });
            });
        </script>

**Comment by Natim** [comment]
Do you feel that you could put together a pull request fixing it?

**Comment by wo0dyn** [comment]
Issue addressed in #30 — Thanks to @marauder37
