### ISSUE TITLE
Highcharts license?

### ISSUE THREAD

**Issue by dhepper** [peopledoc/django-chartjs#33]
What license applies to the bundled version of Highcharts? Highcharts has been non-free software for quite a while and requires a license for non-commercial use. Unfortunately, the link in the highcharts.js file (www.highcharts.com/license) is dead.

**Comment by Natim** [comment]
According to https://shop.highsoft.com/highcharts et is https://creativecommons.org/licenses/by-nc/3.0/

**Comment by dhepper** [comment]
Yes, those are the terms I was referring to. I was hoping that the bundled version of Highcharts was released under a different license. I wanted to use django-chartjs with Chart.js in a commercial client project, but I'm not sure of the legal implications when I pull Highcharts into the project. 

IMHO, the chart libraries should not be part of the package. At least it should be noted in the docs that the bundled Highcharts is not covered by the BSD license.

**Comment by Natim** [comment]
Yes agreed, if you don't use Hightchart, feel free to package django-chartjs without it.
Don't hesitate to file a PR with your proposal.

**Comment by dhepper** [comment]
Ok, I'll do that. Thanks for the quick reply.

**Comment by Natim** [comment]
According to https://web.archive.org/web/20131222193900/http://shop.highsoft.com/highcharts.html it has been CreativeCommons for a while now.
