### ISSUE TITLE
Passing Params

### ISSUE THREAD

**Issue by ACPK** [peopledoc/django-chartjs#38]
How does the chart view accept params?

**Comment by Natim** [comment]
By overriding the get_providers, get_labels and get_data functions. See https://github.com/peopledoc/django-chartjs#2-create-the-view-with-labels-and-data-definition

**Comment by Myzel394** [comment]
It's strange to not be able to pass data dynamically. I would appreciate it, if you could add that function.
For the moment, you can use: `setattr`

example:
```
clicks_per_day_chart = ClicksChartView
setattr(clicks_per_day_chart, "get_labels", clicks_per_day.values())
```
