### ISSUE TITLE
chartjs-plugin-zoom not working 

### ISSUE THREAD

**Issue by pawan7476** [peopledoc/django-chartjs#46]
I'm trying to integrate chartjs-plugin-zoom plugin with my canvas in my django application .I'm getting dataset values from backend API .Canvas is rendered but pan and zoom is not working . There is no error  on the console. 

<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.1"></script>
<script src="https://cdn.jsdelivr.net/npm/hammerjs@2.0.8"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-zoom@0.7.4"></script>

<button type="button" class="btn btn-info collapsed" data-toggle="collapse" data-target="#demo0" >CPU/Mem</button>
<div class="container">
<div id="demo0" class="collapse">
    <div class='row'>
    <div class='col-sm-12' >

        <div class='col-' id="chart-container" class="myChartDiv">
            <canvas id="myChart" width="600" height="400"></canvas>
        </div>
    </div>
    </div>
<br>
    </div>
</div>

<script>
var ctx = document.getElementById('myChart')
var myChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: labels,
                datasets: [{
                    label: 'CPU [avg:'+average(updatedCPU).toFixed(2)+'; min:'+Math.min.apply(null, updatedCPU)+'; max:'+Math.max.apply(null, updatedCPU)+'; {'+percentile+' percentile :'+quantile(updatedCPU, percentile/100).toFixed(2)+' }]',
                    data: updated_cpu,
                    backgroundColor: [

                'rgba(153, 102, 255, 0.2)'

            ],
            borderColor: [

                'rgba(153, 102, 255, 1)'

            ],
            borderWidth: 2,
                    fill: false
                },{
                    label: 'CPS [avg:'+average(updatedCPS).toFixed(2)+'; min:'+Math.min.apply(null, updatedCPS)+'; max:'+Math.max.apply(null, updatedCPS)+'; {'+percentile+' percentile :'+quantile(updatedCPS, percentile/100)+' }]',
                    data: updated_cps,
                    yAxisID: 'A',
                    backgroundColor: [

                'rgba(153, 1190, 255, 0.2)'

            ],
            borderColor: [

                'rgba(153, 1190, 255, 1)'

            ],
            borderWidth: 2
                },{
                    label: 'Memory [avg:'+average(updatedMEM).toFixed(2)+'; min:'+Math.min.apply(null, updatedMEM)+'; max:'+Math.max.apply(null, updatedMEM)+'; {'+percentile+' percentile :'+quantile(updatedMEM, percentile/100).toFixed(2)+' }]',
                    data: updated_mem,
                    backgroundColor: [

                'rgba(255, 99, 132, 0.2)'

            ],
            borderColor: [

                'rgba(255, 99, 132, 1)'

            ],
            borderWidth: 2,
                    fill: false
                }]
            },
    options: {
        title: {
            display: true,
            text: 'PERFAnalyzer',
            fontColor: '#666'
        },
        zoomEnabled: true,
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                },
                scaleLabel: {
                     display: true,
                     labelString: 'CPU - Memory',
                     fontSize: 12
                  }
            }, {
                id: 'A',
                type: 'linear',
                position: 'right',
                ticks: {

          min: 0
        },
                scaleLabel: {
                     display: true,
                     labelString: 'CPS',
                     fontSize: 12
                  }

            }
            ],
            xAxes: [{
                ticks: {
                    beginAtZero: false,
                },
                scaleLabel: {
                     display: true,
                     labelString: 'Date-Time',
                     fontSize: 15
                  }
            }]
        },
       plugins: {
						zoom: {
							pan: {
								enabled: true,
								mode: 'x'
							},
							zoom: {
								enabled: true,
                                //drag: true,
								mode: 'x',
                                speed: 0.1,
							}
						}
					}
    }
        })
</script>

**Comment by nitinnain** [comment]
This is a front-end issue.

**Comment by nitinnain** [comment]
This issue is in the front-end (HTML/JS). Nothing to do with this (django-chartjs) library.
