### ISSUE TITLE
Doughnut chart is uniformly grey

### ISSUE THREAD

**Issue by frague59** [peopledoc/django-chartjs#49]
Hi, 

I'm implementing a doughnut chart, all labels and areas appears grey : the default colors does not applies to the chart.

How can I set colors to both labels and areas ?

Thanks !

**Comment by frague59** [comment]
Have to add that I've a single provider, and as the colors are provider-based, only the first color is set.
Is there a way to use changing colors for this case ? Thanks !

**Comment by Natim** [comment]
I guess the new get_dataset_options released in 5a4f1e0ca53f1296677bbd3da2443a650aa1a401 might help you do that.

**Comment by Natim** [comment]
Thank @edras for it.
