### ISSUE TITLE
Readme doesn't explain what to change in urls.py

### ISSUE THREAD

**Issue by andybak** [peopledoc/django-chartjs#51]
It might be obvious to you but it won't be to some.

**Comment by edras** [comment]
I installed this plugin today and it works fine.
in my urls.py I added two entries:
1. Entry to call templateView:
`path('url_chart_path', TemplateView.as_view(template_name='chart.html'), name='some_name'),`
2. Entry for the AJAX request called in 'chart.html'
`path('json_path', views.LineChartJSONView.as_view(), name='line_chart_json'),`

**Comment by Natim** [comment]
@edras do you feel like adding that in the README?

**Comment by edras** [comment]
Ok, it is done!

**Comment by Natim** [comment]
Fixed in 5a4f1e0ca53f1296677bbd3da2443a650aa1a401
